baseURL = 'https://www.matthewkrueger.com/'
languageCode = 'en-us'
title = 'Matthew Krueger'



[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"


[Params.Sidebar]
subtitle = "Emerging Computer Science Professional | Entrepreneur | Guided by Faith"
emoji = "📓"

[Params.Sidebar.avatar]
src = "img/avatar.jpeg"

[Params.Footer]
customText = "Licensed under GPL, uses open source software. See <a href=\"https://gitlab.com/mckrueg/www.matthewkrueger.com\">GitLab</a> for more."

[menu]
[[menu.social]]
    name = "X"
    url = "https://www.x.com/mckrueg"
    weight = -110
    identifier = "X"
    [menu.social.params]
        icon = "brand-twitter"
        newTab = true
[[menu.social]]
    name = "GitLab"
    url = "https://www.gitlab.com/mckrueg"
    weight = -109
    identifier = "gitlab"
    [menu.social.params]
        icon = "brand-gitlab"
        newTab = true
[[menu.social]]
    name = "GitHub"
    url = "https://www.github.com/Matthew-Krueger"
    weight = -108
    identifier = "github"
    [menu.social.params]
        icon = "brand-github"
        newTab = true
[[menu.social]]
    name = "Email"
    url = "mailto:contact@matthewkrueger.com"
    weight = -107
    identifier = "Email"
    [menu.social.params]
        icon = "mailbox"
        newTab = true
