import { Footer } from "@/components/Footer";
import Navbar from "@/components/NavigationBar";
import StaticSection from "@/components/StaticSection";
import React from "react";
import TaskAnalysisAndApplicationArchitecture_Client from "@/app/cs3240/task-analysis-and-application-architecture/pageClient";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function TaskAnalysisAndApplicationArchitecture() {
    return (
        <div className="motion-background flex flex-col min-h-screen p-8 sm:p-20 font-[family-name:var(--font-geist-sans)] text-slate-950 dark:text-slate-50">
            <Navbar />
            <main className="flex-grow flex flex-col items-center justify-center mt-12">
                <StaticSection>
                    <h1 className="text-4xl font-bold mb-4 text-center">CS 3240 - Usability Engineering</h1>
                    <h2 className="text-2xl font-bold text-center">Task Analysis & Application Architecture Demo</h2>
                    <p>No data leaves your device. All processing happens on the client.</p>
                    <p>Code partially generated by <Link href={"https://grok.com"}>Grok by xAI</Link></p>
                </StaticSection>

                {/* Updated Section with Relevant Information, Visualization Instructions, and Download Button */}
                <StaticSection>
                    <div className="max-w-3xl text-lg">
                        <p>You work for a company that makes custom software for clients. You are a project lead and application architect.</p>
                        <p className="mt-4">
                            One of your clients is a logistics/trucking company that has grown from 5 employees (when you first started working with them) to 35 employees today. The software you write and manage for them has grown organically and is a mish-mash of features, such as:
                        </p>
                        <ul className="list-disc ml-6 mt-2">
                            <li>Scheduling algorithms that give them a competitive advantage</li>
                            <li>Run-of-the-mill business operations like invoicing, customer relationship management, and HR operations (because they don’t like off-the-shelf products)</li>
                            <li>Completely one-off and unique functionality like planning an office party and a “suggestion box” for innovative ideas</li>
                        </ul>
                        <p className="mt-4">
                            The usability problems, confusing menus, and convoluted workflows are starting to impact the business at its current size, so the executives commissioned some user research to help understand how the system is actually being used.
                        </p>
                        <p className="mt-4">
                            Every employee was surveyed about how important 16 key tasks your software does were to them. “Importance” was left up to each employee to decide: how often they did it, how business critical it was, their expertise in performing that task, or something else.
                        </p>
                        <p className="mt-4">
                            Employees were classified by level of “seniority”: “Executives” (5 people), “Managers” (5 people), “Senior level” (15 people), and “Junior level” (10 people). Each employee ranked the tasks (labeled from A to P) from 1-16, with 1 being the most important, 2 the next more important, down to 16 as the least important task to them.
                        </p>
                        <p className="mt-4">
                            This page analyzes the user research data to provide insights into task importance across seniority levels. It creates a visualization of the High, Medium, and Low importance tasks for everyone and for each group, based on average rankings: an average of 5 or less means the task is “High Importance,” an average of 9 or more is “Low Importance,” and everything in between is “Medium Importance.”
                        </p>
                        <div className="mt-4">
                            <div className="flex items-center">
                                <Link href="/cs3240-user-research.csv" download>
                                    <Button>Download Raw Data</Button>
                                </Link>
                            </div>
                        </div>
                    </div>
                </StaticSection>

                <TaskAnalysisAndApplicationArchitecture_Client />
            </main>
            <Footer />
        </div>
    );
}